### ISSUE TITLE
[pyos] Review checklist items

### ISSUE THREAD

**Issue by szhorvat** [python-graphblas/python-graphblas#402]
This is regarding the checklist items for the pyOpenSci review, see https://github.com/pyOpenSci/software-submission/issues/81#issuecomment-1458245662

 - [ ] Could you please add a badge with supported Python versions? Maybe just [![PyPI pyversions](https://img.shields.io/pypi/pyversions/python-graphblas)](https://pypi.python.org/pypi/python-graphblas)? Note to self: 3.11 support is coming, #324.
 - [ ] It would be nice to briefly mention optional dependencies in the [README](https://github.com/python-graphblas/python-graphblas#install), as that's where most people look first (I know they're already in the docs).
 - [ ] Please ensure that the author/maintainer list, as indicated in this repo, matches the author/maintainer list in the submission (see https://github.com/pyOpenSci/software-submission/issues/81#issue-1571161465)

https://github.com/pyOpenSci/software-submission/issues/81

**Comment by szhorvat** [comment]
@eriknw Marginally related: Is the Discord channel, mentioned in the readme, still active / supported? It appears quite dead.

**Comment by eriknw** [comment]
> Is the Discord channel, mentioned in the readme, still active / supported?

Yeah, it's still active/supported. Things often become 1-on-1 pings so the channel doesn't get too noisy with mundane things (but maybe these would be okay to show that we're there?).

The Discord is a perfect place for your recent comments/questions. Sorry I haven't replied yet--I just traveled across the world and am still recovering. I don't know if @jim22k regularly watches the Discord.

**Comment by eriknw** [comment]
Done. Good suggestions, @szhorvat 👍
